### ISSUE TITLE
Windows only?

### ISSUE THREAD

**Issue by juhana** [morissonmaciel/vscode-tsc-compiler#13]
Am I correct in that this extension is for Windows only (or not tested in any other platforms)? It can't find the global installation of Typescript on a Mac and running a local installation in node_modules fails because it uses a Windows-style backslash directory separators (`\`) instead of Unix-style forward slashes (`/`). It tries to find `/node_modules/.bin\tsc` and fails because `\t` is interpreted as a control character.

If this is Windows only, it might be reasonable to mention it in the readme.

**Comment by morissonmaciel** [comment]
@juhana,
Hello. Indeed there were some issues related to malformed cross-platform filesystem paths but was addressed in last pull request.

Perhaps this week will be a newer version of extension adjusting this feature. It's only counting on tests QA.

I'll let know about the updates.

**Comment by morissonmaciel** [comment]
`Addressed in #12 `

**Comment by morissonmaciel** [comment]
Evidences of proper filesystem detection in Mac OS X

<img width="1392" alt="captura de tela 2018-12-04 as 21 29 37" src="https://user-images.githubusercontent.com/11509104/49480337-79692f80-f80d-11e8-88b1-51b985c5cbb9.png">

**Comment by juhana** [comment]
Great to hear that!

The method of generating the path is a bit convoluted, though: the standard method is to use `path.join()` which uses the correct separators automatically (and is generally more robust). For example that line would become simply

    this.tscPath = Path.join(binPath, "tsc");

**Comment by capricorn86** [comment]
It works for me on Ubuntu.

**Comment by morissonmaciel** [comment]
@juhana and @capricorn86 the implementation get a little bit more complex due the workspace root-folder in which `tsconfig.json` is located and the real `node_modules` path for it.

I think the implementation was proper achieved and may attend more scenarios.

**Comment by morissonmaciel** [comment]
New version was released. Please verify if all features listed in change log are attending your case (@juhana)
