### ISSUE TITLE
Have extension honor compileOnSave

### ISSUE THREAD

**Issue by drazisil** [morissonmaciel/vscode-tsc-compiler#4]
I didn't see that it did, but can you have this extension enable and disable based on the `compileOnSave` config option is `jsconfig.json`, as described at the bottom of this page? https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by morissonmaciel** [comment]
Hello @drazisil,
Thanks in advance for this great suggestion. 
Just clarifying: you would like to control de plugin capabilities (in specific `build on save`) using the **tsconfig.json** file from your project folder? Is it correct?

And how about project folders where there isn't any `tsconfig.json` file? How to control it?
🤔
**As an alternate suggestion, what dou you think about having this option as a workspace or VS Code configuration instead?**  

I know having tsconfig.json as a source for standalone configuration is more convenient, but it doesn't cover both scenarios. Also, it can be used in cases where developers are using React with Typescript and are strictly deppendent of Babel, webpack, and so on.

Let me know your thoughts!

**Comment by drazisil** [comment]
I think it would be best to honor the tsconfig.json setting since that is defined as the spec.

I don't see a need for this where projects do not have a tsconfig.json file since it is a feature of that file, and not of Typescript as a whole. Adding it as a config option gives yet another config option to set and remember, vs a setting that is documented officially and should be honored.

As explained in the doc, another compiler extension honors it: https://github.com/TypeStrong/atom-typescript#compile-on-save

**Comment by morissonmaciel** [comment]
I see. I will try to cover both scenarios in a near version, once others suggestions is going around configuring another specific extension features. 
I'll let you know by commenting/changing the issue status. 
Keep tracking and have a nice code!

**Comment by morissonmaciel** [comment]
@drazisil 
You will find a pull request related to your suggestion along with these brand new implementations:

- When extension is lodaded within an workspace **OR** when a change is detected in `tsconfig.json` file the following alert will show:

![image](https://user-images.githubusercontent.com/11509104/47533370-d4f8e280-d889-11e8-94f0-1997286bf2f6.png)

- Two options will be available to control this situation:
-- **Dismiss** : just dismiss the alert until next tsconfig.json file watch event (removal or creation)
-- **Never show again**: dismiss and sets a new entry in workspace configuration file, preventing new alerts to show when future tsconfig.json file watch events occur.

- When `tsconfig.json` file changes with a new **compilerOnSave** option such as:

![image](https://user-images.githubusercontent.com/11509104/47533520-69fbdb80-d88a-11e8-890d-e0bc5b5d1031.png)

Status bar channel for extension updates with a `alert glyph`  along with a disclaimer temporary message: 

![image](https://user-images.githubusercontent.com/11509104/47533574-a62f3c00-d88a-11e8-92a9-eb36decf3799.png)

![image](https://user-images.githubusercontent.com/11509104/47533644-e4c4f680-d88a-11e8-8cd0-a1430c92a1c8.png)

Few free to review Pull Request items (you can't approve, but can review and opine) and let me know if you found something wrong.

Att.
