### ISSUE TITLE
Disable Output window autofocus

### ISSUE THREAD

**Issue by whitesunset** [morissonmaciel/vscode-tsc-compiler#5]
Please add option for disabling Output tab autofocus on each file save. 
Autofocusing output tab during source code editing is really annoying. 

Thanks.

**Comment by morissonmaciel** [comment]
@whitesunset,
Thanks for entering in contact relating this issue/feature suggestion.

Actually, the `Output channel` (tab) autofocus only occurs if there is a build error with `typescript` (tsc) command.
Are you experiencing this issue with this autofocus related to a successful build? 
If so, could you attach some evidencie and repro steps in this issue?

Thanks in advance

**Comment by whitesunset** [comment]
Hello @morissonmaciel !

Yes, I want to disable autofocus when tsc build with errors. Is it possible to add option for this?

**Comment by morissonmaciel** [comment]
@whitesunset 
You will find a pull request related to your suggestion along with these brand new implementations:

- When a compiler is halted by any error, the following alert will be shown:

![image](https://user-images.githubusercontent.com/11509104/47532885-fc4eb000-d887-11e8-9c1c-7b4ae9c32e49.png)

- Tree options will be available to control this situation:
-- **Dismiss** : just dismiss the alert until next build error
--  **Show output**: dismiss and open the Output tab to show last error output from the compiler
-- **Never show again**: dismiss and sets a new entry in workspace configuration file, preventing new alerts to show when future errors occur.

![image](https://user-images.githubusercontent.com/11509104/47533196-2fde0a00-d889-11e8-9d2f-a6e4fefe352c.png)

Few free to review Pull Request items (you can't approve, but can review and opine) and let me know if you found something wrong.

Att.
